// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA66lJNLw9DYOj9leq-JmA3EbdjLNjqYdg',
    appId: '1:908259482025:web:fd8f47a088b148996c8cb8',
    messagingSenderId: '908259482025',
    projectId: 'compudecsi-870bd',
    authDomain: 'compudecsi-870bd.firebaseapp.com',
    storageBucket: 'compudecsi-870bd.firebasestorage.app',
    measurementId: 'G-VLWBR2VNQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCyWC2qzEXDTy5ZMyZZnUJ7KnBai0AEKM',
    appId: '1:908259482025:android:400b1f66656a1fda6c8cb8',
    messagingSenderId: '908259482025',
    projectId: 'compudecsi-870bd',
    storageBucket: 'compudecsi-870bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAafpQ7y1qzlI0ivI_BF-BEEUt4GZY6rcE',
    appId: '1:908259482025:ios:2768c826293253c46c8cb8',
    messagingSenderId: '908259482025',
    projectId: 'compudecsi-870bd',
    storageBucket: 'compudecsi-870bd.firebasestorage.app',
    iosBundleId: 'com.example.compudecsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAafpQ7y1qzlI0ivI_BF-BEEUt4GZY6rcE',
    appId: '1:908259482025:ios:2768c826293253c46c8cb8',
    messagingSenderId: '908259482025',
    projectId: 'compudecsi-870bd',
    storageBucket: 'compudecsi-870bd.firebasestorage.app',
    iosBundleId: 'com.example.compudecsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA66lJNLw9DYOj9leq-JmA3EbdjLNjqYdg',
    appId: '1:908259482025:web:4e6e6ee82489cb446c8cb8',
    messagingSenderId: '908259482025',
    projectId: 'compudecsi-870bd',
    authDomain: 'compudecsi-870bd.firebaseapp.com',
    storageBucket: 'compudecsi-870bd.firebasestorage.app',
    measurementId: 'G-FYT7T8CNBJ',
  );
}
